# !-- ZaphireUHC Configuration file

# This allow to create one or more arenas in server
max_arenas: 1

# Sets the max scenarios number in a game, scenarios # will be selected acording to votes
max_scenarios: 2

# Discord connector allow to send messages to a discord server through a webhooks
# Raw string connector or false to disable
enable_discord: false
discord_connector: ~

# Kraken.io keys - configure this for allow player faces in spectator form
enable_kraken: true
kraken_key: "0c3ecbf8a3458d932e86cc34bb5f8c4e"
kraken_secret: "d86ea5519637b64661819d661462888af3def9ec"

